-- migrate:up

-- PAYMENT TABLE: one transaction per order (docs/build-spec.md §9.1, §9.12).
-- PAYMENT_DETAILS stays the saved card; PAYMENT_ID here names the card used,
-- as in ORDERS.PAYMENT_ID, and is empty for methods that use no card.
CREATE TABLE PAYMENT (
    TRANSACTION_ID  INTEGER
        GENERATED BY DEFAULT AS IDENTITY,
    ORDER_ID        INTEGER NOT NULL,
    PAYMENT_ID      INTEGER,
    AMOUNT          NUMERIC(10,2) NOT NULL CHECK ( AMOUNT >= 0 ),
    METHOD          VARCHAR(20) NOT NULL,
    STATUS          VARCHAR(10) NOT NULL,
    CREATED_AT      TIMESTAMP NOT NULL,
    PRIMARY KEY ( TRANSACTION_ID ),
    CONSTRAINT PYORDERFK FOREIGN KEY ( ORDER_ID )
        REFERENCES ORDERS ( ORDER_ID )
            ON DELETE CASCADE,
    CONSTRAINT PYCARDFK FOREIGN KEY ( PAYMENT_ID )
        REFERENCES PAYMENT_DETAILS ( PAYMENT_ID )
            ON DELETE SET NULL
);

-- migrate:down

DROP TABLE PAYMENT;
